### ISSUE TITLE
Prevent multiple nodecontainers from overlapping

### ISSUE THREAD

**Issue by viperscape** [PistonDevelopers/mush#12]
When nodecontainers overlap, their buttons also can simultaneously react; nodecontainers shouldn't overlap anyway, so we need a way to prevent this during creating and dragging.

**Comment by bvssvni** [comment]
Maybe this can be considered a bug in Conrod?

**Comment by viperscape** [comment]
I was hoping the depth field would alleviate this, but couldn't get depth to work for button-- I think I was doing it wrongly though.

**Comment by viperscape** [comment]
This will close with [merge](https://github.com/PistonDevelopers/mush/pull/24) by using conrod floating canvases, which solves this issue
