### ISSUE TITLE
Move repo under PistonDevelopers?

### ISSUE THREAD

**Issue by stjahns** [PistonDevelopers/mush#3]
I feel like this should (eventually?) be moved into PistonDevelopers for more visibility, but it's your call, @viperscape

**Comment by stjahns** [comment]
If we move it to piston, I can get TravisCI set up and have it automatically deploy docs to https://github.com/PistonDevelopers/docs

**Comment by viperscape** [comment]
Yes sure, what is involved?

**Comment by stjahns** [comment]
I'll see if I can get you added as a PistonDevelopers admin.., then it's just simply transferring ownership of the repo to PistonDevelopers

**Comment by viperscape** [comment]
Okay great

**Comment by viperscape** [comment]
Completed

**Comment by stjahns** [comment]
sweet!
