### ISSUE TITLE
Figure out a crates.io solution

### ISSUE THREAD

**Issue by viperscape** [PistonDevelopers/mush#30]
Someone decided to use Mush on crates.io
https://crates.io/crates/mush/
But looks like the project was abandoned or moved, need to figure out if I can write to this crate name, or what.. :(

**Comment by bvssvni** [comment]
@CraZySacX do you use the mush name on crates.io?

**Comment by CraZySacX** [comment]
I do not.  You can have it.  Not sure how to transfer or let you write to it.

**Comment by viperscape** [comment]
Is the project dead? It had ~500 downloads. Let me try and reach out to someone on irc and see what can be done, thanks

**Comment by CraZySacX** [comment]
It's dead from my perspective.  I was a port of libssh2-sys to that had some fixes for ssh on the Windows platform.  It's now no longer relevant as that has been incorporated into libssh2.

**Comment by steveklabnik** [comment]
@CraZySacX you can add them as an owner, and then have them remove you.

**Comment by CraZySacX** [comment]
Can't find any easy way to add them as owners through crates.io.  Is this something done at the repo level?

**Comment by bvssvni** [comment]
@CraZySacX `cargo owner -a bvssvni`

**Comment by viperscape** [comment]
http://doc.crates.io/crates-io.html#cargo-owner

**Comment by CraZySacX** [comment]
Damn scrolled right past that.  I'll get that done shortly.

**Comment by viperscape** [comment]
Thanks again! Take your time

**Comment by viperscape** [comment]
@bvssvni What's protocol for Piston crates, add the entire team? Also, do I need to do that under this repo, or can it be done from my fork of it? Appreciate you stepping in and helping me on this

**Comment by bvssvni** [comment]
@viperscape I add the PistonDevelopers team once I get ownership. This will give you permissions. You can do `cargo publish` from your fork and it will be updated. However, it is a good idea to merge the changes before publishing.

**Comment by CraZySacX** [comment]
I've added @bvssvni as an owner on the crate.  You can remove me whenever.

**Comment by bvssvni** [comment]
Done.
