### ISSUE TITLE
Consider Dynamo

### ISSUE THREAD

**Issue by viperscape** [PistonDevelopers/mush#31]
I'd like to consider using [Dynamo](https://github.com/pistondevelopers/dynamo), as it matures, with mush. I think it would be interesting to use it as a visual programming language and could both help speed game development and lower the barrier of entry for newer developers with less programming experience. It also seems appealing as it broadens the use case for mush from beyond the initial scope of a visual graph editor to something more.

**Comment by bvssvni** [comment]
This is putting pressure on a language that isn't even born yet. :stuck_out_tongue: Give it 9 months.

**Comment by viperscape** [comment]
That's very understandable, and frankly mush is still being designed before it's even useful yet. It may take that long before it's in a usable state anyway :)

I still like the idea of integrating the dynamic portion into mush, since I feel like setting mush up from static code is a bit of a burden right now. I still have to properly figure out edge guards to prevent a user from connecting incompatible nodes (like float to vec) or connecting them in a incompatible way (like output to output). Or more complex connection logic like certain composite nodes cannot link together (like say an event trigger and material node). This will likely still require a runtime assertion.. something like this seems it might be easier if it was designed with a runtime vm in mind. No pressure though, just discussing concepts :)
