### ISSUE TITLE
Update dependencies

### ISSUE THREAD

**Issue by bvssvni** [PistonDevelopers/mush#36]
I got this ready once https://github.com/PistonDevelopers/conrod/pull/710 is landed.

**Comment by viperscape** [comment]
great thanks, the introduction of rusttype in pace of freetype is exciting.

**Comment by bvssvni** [comment]
@viperscape @mitchmindtree Are you on IRC (#rust-gamedev)? I want to talk about the upgrade and might need some help.

**Comment by mitchmindtree** [comment]
@bvssvni I'm not on IRC as I'm a bit busy atm, but can check back here intermittently to help 👍
