### ISSUE TITLE
redesign and rewrite

### ISSUE THREAD

**Issue by viperscape** [PistonDevelopers/mush#37]
This crate is obviously dead at this point for lack of interest or development, but of course I now want to resurrect it since I have renewed interest. The new design would require an entire rewrite, likely dropping conrod in favor of a simpler gui: [imgui-rs](https://github.com/Gekkio/imgui-rs), and primarily targeting my other library [lichen](https://github.com/viperscape/lichen). The new design would still be very agnostic, and hopefully would not require lichen as long as some predefined traits were met. This also means I'd drop, entirely, the graph backends I built here. Ultimately this entails an entire rewrite, something I'm comfortable with a this point as converting this library over would be messy and probably unnecessary at this point-- a rewrite would be more succinct and clear.

If this seems unacceptable let me know! Let's discuss below, if needed :-)

@stjahns @bvssvni

**Comment by viperscape** [comment]
Also, if this is a go, I'll need to be a collaborator on crates.io so I can push and have docs generate.

**Comment by bvssvni** [comment]
Go ahead! This project is currently dead anyway.

The PistonCollaborator team is added to crates.io. You are already added as collaborator.

**Comment by viperscape** [comment]
Great thanks. I'll close this, feel free to reopen to restart discussion!
