### ISSUE TITLE
Rename the executable binary to 'test' or 'example'

### ISSUE THREAD

**Issue by stjahns** [PistonDevelopers/mush#8]
`cargo doc` apparently doesn't like having both a binary and a library with the same name in the same crate, see
https://travis-ci.org/PistonDevelopers/mush/builds/60995325#L294

**Comment by viperscape** [comment]
Ok, yea I was thinking having it as a lib and executable is pushing it-- but it makes sense to abstract as much to a lib format for reuse. I suppose we should include cargo.lock?

**Comment by stjahns** [comment]
Fixed by https://github.com/PistonDevelopers/mush/pull/16
